### ISSUE TITLE
Can't connect this library and php

### ISSUE THREAD

**Issue by IBleSSeDI** [3rd-Eden/memcached#254]
We have a php application. And we use memcache. In our system node.js writes to cache and php reads from cache. But I get the following error in php:

MemcachePool::get(): Failed to uncompress data

In node memcache module I addedkeyCompression

new Memcached(host + ':' + port, {keyCompression: false});

But seams like node.js compresses data to memcache and php cannot read it correctly. How to fix that? Thanks.

**Comment by 3rd-Eden** [comment]
Well, it has nothing to do with PHP vs Node.js here. It's because the Memcached specification does not instruct library authors on how compress values. This extra meta data is usually passed in by flags on the  stored memcached data. It could be that there's a miss match in flags, or that a completely different compression algorithm is used (as node's core only ships with zlib). Best advice I can give is that when you need compatibility between various of languages it's best to store data as plain text.

**Comment by IBleSSeDI** [comment]
Yes, setting data as a string works. Thanks.
