### ISSUE TITLE
How to Install node-memcached ?

### ISSUE THREAD

**Issue by sungyism** [3rd-Eden/memcached#85]
How to Install node-memcached ?
Detailed steps

**Comment by kswope** [comment]
I agree with seriousManual.  There is no reverse lookup of this repo back to the npm package.  I actually had to find this issue report just to figure out it out.  Especially since this repo is called "node-memcached" and the npm package is called "memcached".  Actually I'm still not even sure I installed the same package!

Just put this in the docs and save a lot of people the aggravation:

```
npm install memcached
```

**Comment by 3rd-Eden** [comment]
Renamed the repo to just memcached
